---
# Kooha screen recorder installation via Flatpak

- name: Ensure Flatpak is available
  ansible.builtin.package:
    name: flatpak
    state: present
  become: yes
  when: app_states['kooha'] | default('present') == 'present'

- name: Ensure Flathub repository exists
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: yes
  when: app_states['kooha'] | default('present') == 'present'

- name: Install Kooha
  community.general.flatpak:
    name: io.github.seadve.Kooha
    state: present
    remote: flathub
  become: yes
  when: app_states['kooha'] | default('present') == 'present'

- name: Remove Kooha
  community.general.flatpak:
    name: io.github.seadve.Kooha
    state: absent
  become: yes
  when: app_states['kooha'] | default('present') == 'absent'
