---
# eza installation - modern replacement for ls
# https://github.com/eza-community/eza

- name: Install eza
  ansible.builtin.apt:
    name: eza
    state: present
  become: true
  when: app_states['eza'] | default('present') == 'present'

# Fish shell integration
- name: Create fish conf.d directory
  ansible.builtin.file:
    path: "{{ user.home }}/.config/fish/conf.d"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
  when: app_states['eza'] | default('present') == 'present'

- name: Deploy fish aliases for eza
  ansible.builtin.template:
    src: eza.fish.j2
    dest: "{{ user.home }}/.config/fish/conf.d/eza.fish"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
  when: app_states['eza'] | default('present') == 'present'

# Cleanup when absent
- name: Remove eza when absent
  ansible.builtin.apt:
    name: eza
    state: absent
    purge: true
  become: true
  when: app_states['eza'] | default('present') == 'absent'

- name: Remove fish aliases for eza when absent
  ansible.builtin.file:
    path: "{{ user.home }}/.config/fish/conf.d/eza.fish"
    state: absent
  when: app_states['eza'] | default('present') == 'absent'
