---
# aha Pake App installation
# Debian package deployment

- name: Uninstall aha for reinstall
  apt:
    name: aha
    state: absent
  become: yes
  when: app_states['aha'] | default('present') == 'present'
  tags: ["never", "reinstall"]

- name: Install aha .deb package
  apt:
    deb: "{{ role_path }}/files/aha.deb"
    state: present
  become: yes
  when: app_states['aha'] | default('present') == 'present'
  tags: ["always"]

- name: Remove .deb desktop files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/share/applications/aha.desktop
    - /usr/share/applications/com.pake.aha.desktop
  become: yes
  when: app_states['aha'] | default('present') == 'present'

- name: Remove .deb icon files (all sizes)
  shell: find /usr/share/icons/hicolor -name 'pake-aha.png' -delete
  become: yes
  when: app_states['aha'] | default('present') == 'present'
  changed_when: false

- name: Install custom desktop file
  copy:
    src: pake-aha.desktop
    dest: /usr/share/applications/pake-aha.desktop
    mode: '0644'
  become: yes
  when: app_states['aha'] | default('present') == 'present'

- name: Install themed icons at all sizes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: 'pake-aha-icon-16.png', dest: '/usr/share/icons/hicolor/16x16/apps/pake-aha.png' }
    - { src: 'pake-aha-icon-32.png', dest: '/usr/share/icons/hicolor/32x32/apps/pake-aha.png' }
    - { src: 'pake-aha-icon-48.png', dest: '/usr/share/icons/hicolor/48x48/apps/pake-aha.png' }
    - { src: 'pake-aha-icon-64.png', dest: '/usr/share/icons/hicolor/64x64/apps/pake-aha.png' }
    - { src: 'pake-aha-icon-128.png', dest: '/usr/share/icons/hicolor/128x128/apps/pake-aha.png' }
    - { src: 'pake-aha-icon-256.png', dest: '/usr/share/icons/hicolor/256x256/apps/pake-aha.png' }
    - { src: 'pake-aha-icon-512.png', dest: '/usr/share/icons/hicolor/512x512/apps/pake-aha.png' }
    - { src: 'pake-aha-icon-800.png', dest: '/usr/share/icons/hicolor/800x800/apps/pake-aha.png' }
  become: yes
  when: app_states['aha'] | default('present') == 'present'

- name: Update icon cache
  command: gtk-update-icon-cache -f /usr/share/icons/hicolor
  become: yes
  when: app_states['aha'] | default('present') == 'present'
  changed_when: false

# Cleanup when absent
- name: Remove aha Pake app
  apt:
    name: aha
    state: absent
  become: yes
  when: app_states['aha'] | default('present') == 'absent'

