---
# kong-email Pake App installation
- name: Install kong-email .deb package
  ansible.builtin.apt:
    deb: "{{ role_path }}/files/kong-email.deb"
    state: present
  become: true
  when: app_states['kong_email'] | default('present') == 'present'

- name: Remove .deb desktop files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/share/applications/kong-email.desktop
    - /usr/share/applications/com.pake.kong-email.desktop
  become: true
  when: app_states['kong_email'] | default('present') == 'present'

- name: Install custom desktop file and icons
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: "pake-kong-email.desktop", dest: "/usr/share/applications/pake-kong-email.desktop" }
    - { src: "pake-kong-email-icon-16.png", dest: "/usr/share/icons/hicolor/16x16/apps/pake-kong-email.png" }
    - { src: "pake-kong-email-icon-32.png", dest: "/usr/share/icons/hicolor/32x32/apps/pake-kong-email.png" }
    - { src: "pake-kong-email-icon-48.png", dest: "/usr/share/icons/hicolor/48x48/apps/pake-kong-email.png" }
    - { src: "pake-kong-email-icon-64.png", dest: "/usr/share/icons/hicolor/64x64/apps/pake-kong-email.png" }
    - { src: "pake-kong-email-icon-128.png", dest: "/usr/share/icons/hicolor/128x128/apps/pake-kong-email.png" }
    - { src: "pake-kong-email-icon-256.png", dest: "/usr/share/icons/hicolor/256x256/apps/pake-kong-email.png" }
    - { src: "pake-kong-email-icon-512.png", dest: "/usr/share/icons/hicolor/512x512/apps/pake-kong-email.png" }
    - { src: "pake-kong-email-icon-800.png", dest: "/usr/share/icons/hicolor/scalable/apps/pake-kong-email.png" }
  become: true
  when: app_states['kong_email'] | default('present') == 'present'
  notify: Update icon cache

# Cleanup when absent
- name: Remove kong-email Pake app
  ansible.builtin.apt:
    name: kong-email
    state: absent
  become: true
  when: app_states['kong_email'] | default('present') == 'absent'
