---
# Nala package manager installation
# Nala is a front-end for libapt-pkg using the python-apt API

- name: Install nala package manager
  ansible.builtin.apt:
    name: nala
    state: present
    update_cache: true
  become: true

  tags: [system]
