---
# Python packages installation

- name: Install Python development packages
  apt:
    name: "{{ dev_packages }}"
    state: present
  become: yes
  tags: [system]

- name: Install Python packages via pip
  pip:
    name: "{{ python_packages }}"
    state: present
    extra_args: --user
  become: yes
  become_user: "{{ user.name }}"
  when: python_packages is defined

  tags: [system]