---
# Python packages installation

- name: Install Python development packages
  ansible.builtin.apt:
    name: "{{ dev_packages }}"
    state: present
  become: true
  tags: [system]

- name: Install Python packages via pip
  ansible.builtin.pip:
    name: "{{ python_packages }}"
    state: present
    extra_args: --user
  become: true
  become_user: "{{ user.name }}"
  when: python_packages is defined

  tags: [system]
