---
# Zellij terminal multiplexer installation and configuration

- name: Install zellij from GitHub
  ansible.builtin.include_tasks: ../../system/tasks/includes/github_release.yml
  vars:
    org: zellij-org
    repo: zellij
    binary_name: zellij
    filename_substring: x86_64-unknown-linux-musl.tar.gz
  when: app_states.zellij | default('present') == 'present'

- name: Create zellij config directory
  ansible.builtin.file:
    path: "{{ user.home }}/.config/zellij"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
  become: true
  when: app_states.zellij | default('present') == 'present'

- name: Deploy zellij config
  ansible.builtin.template:
    src: config.kdl.j2
    dest: "{{ user.home }}/.config/zellij/config.kdl"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
  become: true
  when: app_states.zellij | default('present') == 'present'

- name: Remove zellij binary when absent
  ansible.builtin.file:
    path: /usr/local/bin/zellij
    state: absent
  when: app_states.zellij | default('present') == 'absent'
  become: true

- name: Remove zellij config when absent
  ansible.builtin.file:
    path: "{{ user.home }}/.config/zellij"
    state: absent
  when: app_states.zellij | default('present') == 'absent'
  become: true
