---
# avanti Pake App installation
- name: Install avanti .deb package
  ansible.builtin.apt:
    deb: "{{ role_path }}/files/avanti.deb"
    state: present
  become: true
  when: app_states['avanti'] | default('present') == 'present'

- name: Remove .deb desktop files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/share/applications/avanti.desktop
    - /usr/share/applications/com.pake.avanti.desktop
  become: true
  when: app_states['avanti'] | default('present') == 'present'
  tags: [avanti, apps, config]

- name: Install custom desktop file and icons
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: "pake-avanti.desktop", dest: "/usr/share/applications/pake-avanti.desktop" }
    - { src: "pake-avanti-icon-16.png", dest: "/usr/share/icons/hicolor/16x16/apps/pake-avanti.png" }
    - { src: "pake-avanti-icon-32.png", dest: "/usr/share/icons/hicolor/32x32/apps/pake-avanti.png" }
    - { src: "pake-avanti-icon-48.png", dest: "/usr/share/icons/hicolor/48x48/apps/pake-avanti.png" }
    - { src: "pake-avanti-icon-64.png", dest: "/usr/share/icons/hicolor/64x64/apps/pake-avanti.png" }
    - { src: "pake-avanti-icon-128.png", dest: "/usr/share/icons/hicolor/128x128/apps/pake-avanti.png" }
    - { src: "pake-avanti-icon-256.png", dest: "/usr/share/icons/hicolor/256x256/apps/pake-avanti.png" }
    - { src: "pake-avanti-icon-512.png", dest: "/usr/share/icons/hicolor/512x512/apps/pake-avanti.png" }
    - { src: "pake-avanti-icon-800.png", dest: "/usr/share/icons/hicolor/scalable/apps/pake-avanti.png" }
  become: true
  when: app_states['avanti'] | default('present') == 'present'
  notify: Update icon cache

# Cleanup when absent
- name: Remove avanti Pake app
  ansible.builtin.apt:
    name: avanti
    state: absent
  become: true
  when: app_states['avanti'] | default('present') == 'absent'
