---
# github Pake App installation
- name: Install github .deb package
  ansible.builtin.apt:
    deb: "{{ role_path }}/files/github.deb"
    state: present
  become: true
  when: app_states['github'] | default('present') == 'present'

- name: Remove .deb desktop files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/share/applications/github.desktop
    - /usr/share/applications/com.pake.github.desktop
  become: true
  when: app_states['github'] | default('present') == 'present'

- name: Install custom desktop file and icons
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: "pake-github.desktop", dest: "/usr/share/applications/pake-github.desktop" }
    - { src: "pake-github-icon-16.png", dest: "/usr/share/icons/hicolor/16x16/apps/pake-github.png" }
    - { src: "pake-github-icon-32.png", dest: "/usr/share/icons/hicolor/32x32/apps/pake-github.png" }
    - { src: "pake-github-icon-48.png", dest: "/usr/share/icons/hicolor/48x48/apps/pake-github.png" }
    - { src: "pake-github-icon-64.png", dest: "/usr/share/icons/hicolor/64x64/apps/pake-github.png" }
    - { src: "pake-github-icon-128.png", dest: "/usr/share/icons/hicolor/128x128/apps/pake-github.png" }
    - { src: "pake-github-icon-256.png", dest: "/usr/share/icons/hicolor/256x256/apps/pake-github.png" }
    - { src: "pake-github-icon-512.png", dest: "/usr/share/icons/hicolor/512x512/apps/pake-github.png" }
    - { src: "pake-github-icon-800.png", dest: "/usr/share/icons/hicolor/scalable/apps/pake-github.png" }
  become: true
  when: app_states['github'] | default('present') == 'present'
  notify: Update icon cache

# Cleanup when absent
- name: Remove github Pake app
  ansible.builtin.apt:
    name: github
    state: absent
    purge: true
  become: true
  when: app_states['github'] | default('present') == 'absent'

- name: Remove custom desktop file and icons
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/share/applications/pake-github.desktop
    - /usr/share/applications/github.desktop
    - /usr/share/applications/com.pake.github.desktop
    - /usr/share/icons/hicolor/16x16/apps/pake-github.png
    - /usr/share/icons/hicolor/32x32/apps/pake-github.png
    - /usr/share/icons/hicolor/48x48/apps/pake-github.png
    - /usr/share/icons/hicolor/64x64/apps/pake-github.png
    - /usr/share/icons/hicolor/128x128/apps/pake-github.png
    - /usr/share/icons/hicolor/256x256/apps/pake-github.png
    - /usr/share/icons/hicolor/512x512/apps/pake-github.png
    - /usr/share/icons/hicolor/scalable/apps/pake-github.png
  become: true
  when: app_states['github'] | default('present') == 'absent'
  notify: Update icon cache
